# Generated by Django 3.0.5 on 2020-04-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Aadhar_Number', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Phone_Number', models.CharField(max_length=200)),
                ('Age', models.IntegerField(default=0)),
                ('Sex', models.CharField(max_length=5)),
            ],
        ),
    ]
