# Generated by Django 3.0.5 on 2020-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Profile_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profiles/'),
        ),
    ]
